---
verbosity: "off"
address: 0.0.0.0:2053
script: |
  pub async fn route(upstreams, inited, ctx, query) {
    if inited.domain.0.contains(query.first_question?.qname) {
       upstreams.send_default("domestic", query).await
    } else {
       upstreams.send("secure", CacheMode::Persistent, query).await
    }
  }

  pub async fn init() {
    let domain = Domain::new();
    domain.add_file("../data/china.txt")?;
    Ok(#{"domain": Utils::Domain(domain)})
  }


upstreams:
  domestic:
    udp:
      addr: 114.114.114.114:53
      timeout: 1
  secure:
    https:
      timeout: 2
      uri: https://dns.quad9.net/dns-query
      addr: 9.9.9.9
