---
verbosity: "off"
address: 0.0.0.0:2053
script:
  init: |
    let domain = new_domain_list().add_file("../data/china.txt").seal();
  route: |
    if domain.contains(query.first_question.qname) {
       upstreams.send("domestic", query)
    } else {
       upstreams.send("secure", "persistent", query)
    };

upstreams:
  domestic:
    udp:
      addr: 114.114.114.114:53
      timeout: 1
  secure:
    https:
      timeout: 2
      uri: https://dns.quad9.net/dns-query
      addr: 9.9.9.9
