---
verbosity: "off"
address: 0.0.0.0:2053
script:
  route: |
    if query.header.opcode == "QUERY" {
       upstreams.send("secure", query)
    };
upstreams:
  secure:
    https:
      timeout: 2
      uri: https://dns.quad9.net/dns-query
      addr: 9.9.9.9
