---
verbosity: "off"
address: 0.0.0.0:2053
script:
  init: |
    let geoip = new_geoip_from_path("../data/full.mmdb").seal();
  route: |
    let resp = upstreams.send("domestic", query);

    try {
      let ans = resp.answer[0];
      return switch ans.rtype.to_string() {
        "A" if !geoip.contains(ans.to_a().ip, "CN") => { upstreams.send("secure", query) }
        "AAAA" if !geoip.contains(ans.to_aaaa().ip, "CN") => { upstreams.send("secure", query) }
        _ => resp
      };
    } catch(err) {
      print(err);
      return resp;
    }

upstreams:
  domestic:
    udp:
      addr: 114.114.114.114:53
      timeout: 1
  secure:
    https:
      timeout: 2
      uri: https://dns.quad9.net/dns-query
      addr: 9.9.9.9
