---
verbosity: "off"
address: 0.0.0.0:2053
script: |
  pub async fn route(upstreams, inited, ctx, query) {
    if query.header.opcode.to_str() == "QUERY" {
      upstreams.send_default("secure", query).await
    }
  }

upstreams:
  secure:
    https:
      timeout: 2
      uri: https://dns.quad9.net/dns-query
      addr: 9.9.9.9
